name: Run dbt Models

on:
  workflow_dispatch:  # allow manual trigger
  schedule:
    - cron: '0 6 * * *'  # run daily at 6 AM UTC

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dbt dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-snowflake

      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          spotify_models:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: ${{ secrets.DBT_ACCOUNT }}
                user: ${{ secrets.DBT_USER }}
                password: ${{ secrets.DBT_PASSWORD }}
                role: ${{ secrets.DBT_ROLE }}
                database: ${{ secrets.DBT_DATABASE }}
                warehouse: ${{ secrets.DBT_WAREHOUSE }}
                schema: ${{ secrets.DBT_SCHEMA }}
                authenticator: ${{ secrets.DBT_AUTHENTICATOR }}
          EOF

      - name: Run dbt models
        run: dbt run --project-dir spotify_models
